ITSupportTicket/Controllers/AssignedController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITSupportTicket;

namespace ITSupportTicket.Controllers
{
    public class AssignedController : Controller
    {
        private MyCon db = new MyCon();

        // GET: Assigned
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var tblAssigneds = db.tblAssigneds.Include(t => t.tblTicket);
            return View(tblAssigneds.ToList());
        }

        [Authorize(Roles = "Staff")]
        public ActionResult AssignedT()
        {
            var tblAssigneds = db.tblAssigneds.Include(t => t.tblTicket).Where(p => p.Email == User.Identity.Name);
            return View(tblAssigneds.ToList());
        }

        // GET: Assigned/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblAssigned tblAssigned = db.tblAssigneds.Find(id);
            if (tblAssigned == null)
            {
                return HttpNotFound();
            }
            return View(tblAssigned);
        }

        // GET: Assigned/Create
        public ActionResult Create()
        {
            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name");
            return View();
        }

        // POST: Assigned/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AssignedId,TicketId,StaffName,Email")] tblAssigned tblAssigned)
        {
            if (ModelState.IsValid)
            {
                db.tblAssigneds.Add(tblAssigned);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name", tblAssigned.TicketId);
            return View(tblAssigned);
        }

        // GET: Assigned/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblAssigned tblAssigned = db.tblAssigneds.Find(id);
            if (tblAssigned == null)
            {
                return HttpNotFound();
            }
            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name", tblAssigned.TicketId);
            return View(tblAssigned);
        }

        // POST: Assigned/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AssignedId,TicketId,StaffName,Email")] tblAssigned tblAssigned)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblAssigned).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name", tblAssigned.TicketId);
            return View(tblAssigned);
        }

        // GET: Assigned/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblAssigned tblAssigned = db.tblAssigneds.Find(id);
            if (tblAssigned == null)
            {
                return HttpNotFound();
            }
            return View(tblAssigned);
        }

        // POST: Assigned/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblAssigned tblAssigned = db.tblAssigneds.Find(id);
            db.tblAssigneds.Remove(tblAssigned);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITSupportTicket/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITSupportTicket;

namespace ITSupportTicket.Controllers
{
    public class CommentController : Controller
    {
        private MyCon db = new MyCon();

        // GET: Comment
        [Authorize]
        public ActionResult Index()
        {
            var tblComments = db.tblComments.Include(t => t.tblTicket);
            return View(tblComments.ToList());
        }
        [Authorize]
        public ActionResult Feedback()
        {
            var tblComments = db.tblComments.Include(t => t.tblTicket);
            return View(tblComments.ToList());
        }

        // GET: Comment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblComment tblComment = db.tblComments.Find(id);
            if (tblComment == null)
            {
                return HttpNotFound();
            }
            return View(tblComment);
        }

        // GET: Comment/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name");
            return View();
        }

        // POST: Comment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentsId,TicketId,Name,Comments")] tblComment tblComment)
        {
            if (ModelState.IsValid)
            {
                db.tblComments.Add(tblComment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name", tblComment.TicketId);
            return View(tblComment);
        }

        // GET: Comment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblComment tblComment = db.tblComments.Find(id);
            if (tblComment == null)
            {
                return HttpNotFound();
            }
            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name", tblComment.TicketId);
            return View(tblComment);
        }

        // POST: Comment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentsId,TicketId,Name,Comments")] tblComment tblComment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblComment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TicketId = new SelectList(db.tblTickets, "TicketId", "Name", tblComment.TicketId);
            return View(tblComment);
        }

        // GET: Comment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblComment tblComment = db.tblComments.Find(id);
            if (tblComment == null)
            {
                return HttpNotFound();
            }
            return View(tblComment);
        }

        // POST: Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblComment tblComment = db.tblComments.Find(id);
            db.tblComments.Remove(tblComment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITSupportTicket/Controllers/EmailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITSupportTicket;

namespace ITSupportTicket.Controllers
{
    public class EmailController : Controller
    {
        private MyCon db = new MyCon();

        // GET: Email
        [Authorize]
        public ActionResult Index()
        {
            return View(db.tblEmails.ToList());
        }
        [Authorize(Roles = "Staff")]
        public ActionResult StaffMessage()
        {
            return View(db.tblEmails.ToList());
        }


        // GET: Email/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblEmail tblEmail = db.tblEmails.Find(id);
            if (tblEmail == null)
            {
                return HttpNotFound();
            }
            return View(tblEmail);
        }

        // GET: Email/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Email/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmailId,From,To,Message")] tblEmail tblEmail)
        {
            if (ModelState.IsValid)
            {
                db.tblEmails.Add(tblEmail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblEmail);
        }

        // GET: Email/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblEmail tblEmail = db.tblEmails.Find(id);
            if (tblEmail == null)
            {
                return HttpNotFound();
            }
            return View(tblEmail);
        }

        // POST: Email/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmailId,From,To,Message")] tblEmail tblEmail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblEmail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblEmail);
        }

        // GET: Email/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblEmail tblEmail = db.tblEmails.Find(id);
            if (tblEmail == null)
            {
                return HttpNotFound();
            }
            return View(tblEmail);
        }

        // POST: Email/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblEmail tblEmail = db.tblEmails.Find(id);
            db.tblEmails.Remove(tblEmail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITSupportTicket/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ITSupportTicket;

namespace ITSupportTicket.Controllers
{
    public class TicketController : Controller
    {
        private MyCon db = new MyCon();

        // GET: Ticket
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.tblTickets.ToList());
        }

        // GET: Ticket/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTicket tblTicket = db.tblTickets.Find(id);
            if (tblTicket == null)
            {
                return HttpNotFound();
            }
            return View(tblTicket);
        }

        // GET: Ticket/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TicketId,Name")] tblTicket tblTicket)
        {
            if (ModelState.IsValid)
            {
                db.tblTickets.Add(tblTicket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblTicket);
        }

        // GET: Ticket/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTicket tblTicket = db.tblTickets.Find(id);
            if (tblTicket == null)
            {
                return HttpNotFound();
            }
            return View(tblTicket);
        }

        // POST: Ticket/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TicketId,Name")] tblTicket tblTicket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblTicket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblTicket);
        }

        // GET: Ticket/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTicket tblTicket = db.tblTickets.Find(id);
            if (tblTicket == null)
            {
                return HttpNotFound();
            }
            return View(tblTicket);
        }

        // POST: Ticket/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblTicket tblTicket = db.tblTickets.Find(id);
            db.tblTickets.Remove(tblTicket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITSupportTicket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - IT Support</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Bootstrap CSS -->
    <link href="~/Theme/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="~/Theme/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="~/Theme/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="~/Theme/css/style.css" rel="stylesheet">
    <link href="~/Theme/css/style-responsive.css" rel="stylesheet" />






</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Software Support Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Users Feedback", "Feedback", "Comment")</li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <!-- container section start -->
    <section id="container" class="">
        <!--header start-->

        @*<header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i> </div>

            </div>

            <!--logo start-->
            <a href="index.html" class="logo"><span class="lite">Admin Panel</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">


                <!-- notificatoin dropdown end-->
            </div>


        </header>*@
        <!--header end-->
        <!--sidebar start-->

        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">
                    <li class="">
                        
                    </li>


                    


                    <li class="sub-menu">
                        <a href="javascript:;" class="@*btn btn-info*@">
                            <i class="icon_desktop"></i>
                            <span>User</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            @*<li><a class="" href="form_component.html">Form Elements</a></li>
                <li><a class="" href="form_validation.html">Form Validation</a></li>*@

                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Submit Ticket", "Index", "SubmitTicket")</li>
                            <li>@Html.ActionLink("View Ticket", "Index", "SubmitTicket")</li>
                            
                            <li>@Html.ActionLink("View Solve Ticket", "ViewSolve", "StaffTicket")</li>
                            <li>@Html.ActionLink("Message", "Index", "Email")</li>
                            <li>@Html.ActionLink("Comment", "Index", "Comment")</li>
                            


                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_document_alt"></i>
                            <span>Admin</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            @*<li><a class="" href="form_component.html">Form Elements</a></li>
        <li><a class="" href="form_validation.html">Form Validation</a></li>*@

                            <li>@Html.ActionLink("Ticket ID", "Index", "Ticket")</li>

                            <li>@Html.ActionLink("View Ticket", "AdminView", "SubmitTicket")</li>

                            <li>@Html.ActionLink("View Solve Ticket", "ViewSolveAdmin", "StaffTicket")</li>
                            <li>@Html.ActionLink("Message", "Index", "Email")</li>

                            <li>@Html.ActionLink("Assigned to Staff", "Index", "Assigned")</li>
                            <li>@Html.ActionLink("Submitted Ticket Report", "Report", "SubmitTicket")</li>
                            <li>@Html.ActionLink("Solved Ticket Report", "SolveReport", "StaffTicket")</li>
                            
                            <li>@Html.ActionLink("Staff Wise Report", "StaffDailyR", "StaffWiseReport")</li>




                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_document_alt"></i>
                            <span>Staff</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            @*<li><a class="" href="form_component.html">Form Elements</a></li>
        <li><a class="" href="form_validation.html">Form Validation</a></li>*@

                            <li>@Html.ActionLink("Assigned Ticket", "AssignedT", "Assigned")</li>

                            <li>@Html.ActionLink("View Ticket", "StaffView", "SubmitTicket")</li>
                            <li>@Html.ActionLink("Solve Ticket", "Index", "StaffTicket")</li>
                            <li>@Html.ActionLink("View Solve Ticket", "Index", "StaffTicket")</li>
                            <li>@Html.ActionLink("Message", "StaffMessage", "Email")</li>
                            
                            <li>@Html.ActionLink("All Report", "Index", "StaffWiseReport")</li>





                        </ul>
                    </li>
                    @*<li>
            <a class="" href="widgets.html">
                <i class="icon_genius"></i>
                <span>Widgets</span>
            </a>
        </li>*@
                    @*<li>
            <a class="" href="chart-chartjs.html">
                <i class="icon_piechart"></i>
                <span>Charts</span>

            </a>

        </li>*@

                    
                    










                            @*<li><a class="" href="profile.html">Profile</a></li>
                <li><a class="" href="login.html"><span>Login Page</span></a></li>
                <li><a class="active" href="blank.html">Blank Page</a></li>
                <li><a class="" href="404.html">404 Error</a></li>*@
                     

                
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">

                <!-- page start-->
                @RenderBody()


                <!-- page end-->
            </section>
        </section>
        <!--main content end-->

    </section>
    <!-- container section end -->
    <!-- javascripts -->
    <script src="~/Theme/js/jquery.js"></script>
    <script src="~/Theme/js/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <!-- nice scroll -->
    <script src="~/Theme/js/jquery.scrollTo.min.js"></script>
    <script src="~/Theme/js/jquery.nicescroll.js" type="text/javascript"></script><!--custome script for all page-->
    <script src="~/Theme/js/scripts.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>